[package]
name = "gene"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Crate providing a log matching framework written in Rust"
documentation = "https://docs.rs/gene"
readme.workspace = true
repository.workspace = true
license.workspace = true
keywords = [
  "log-processing",
  "security",
  "signature-engine",
  "threat-detection",
]

[[bench]]
harness = false
name = "engine_benchmark"

[dependencies]
gene_derive = { path = "../derive", version = "0.7.5" }
lazy_static = "1.4.0"
pest = "2.7.15"
pest_derive = "2.7.15"
regex = "1.10.2"
serde = { version = "1.0.192", features = ["derive"] }
serde_yaml = { version = "0.9.27" }
thiserror = "1.0.50"
uuid = { version = "1.27.0", optional = true }

[dev-dependencies]
criterion = "0.5.1"
libflate = "2.0.0"
serde_json = "1.0.108"
